site_name: Gap-ML
theme: readthedocs
repo_url: https://github.com/andrewferlitsch/Gap
google_analytics: ['UA-124105572-1', 'https://andrewferlitsch.github.io/Gap/']
pages:
- Home: index.md
- About: about.md
- quick start guide: quick-start-guide.md
- specifications:
    - Segmentation: specs/segmentation_spec.md
    - Splitter: specs/splitter_spec.md
    - Syntax: specs/syntax_spec.md
    - Vision: specs/vision_spec.md
- Tutorials:
    - Computer Vision: tutorials/computer_vision.md
